#!/bin/sh
# $Id: postinst 125 2008-04-06 19:20:02Z robert $
# postinst for doc-base

# Abort if any command returns an error value
set -e

package=doc-base
# upgrades prior to this version require complete re-registration
compat_ver=0.8.12~
VERBOSE=

ctrldir="/usr/share/$package"
infodir="/var/lib/$package/info"
docsdir="/var/lib/$package/documents"

if [ "$DEBUG" ]; then
    echo entering $package postinst
    set -x
fi

reinstall_docs () {
    install-docs ${VERBOSE} "--install-$1"
}

register_our_docs () {
    install-docs ${VERBOSE} --install $ctrldir/$package	\
		  		      $ctrldir/install-docs-man
}

case "$1" in
  configure)

    if dpkg --compare-versions "$2" lt-nl "$compat_ver" ||
      [ ! -f "$infodir/status.db"  ]; then
	# version is less than last compatable version, we need to
	# re-register all the docs
        reinstall_docs all
#    else
        # only register our stuff		# registering our docs should be 
#	register_our_docs			# handled by triggers 
	
    fi
    ;;
  triggered)
    if [ -f "$infodir/status.db" ]; then
	    reinstall_docs changed
    else
    	echo "doc-base seems not to be configured yet, skipping triggers run"
    fi
    ;; 	
esac

#DEBHELPER#

exit 0
