#!/bin/sh
# $Id: postinst 115 2008-03-31 18:16:38Z robert $
# postinst for doc-base

# Abort if any command returns an error value
set -e

package=doc-base
# upgrades prior to this version require complete re-registration
compat_ver=0.8.10
VERBOSE=

ctrldir="/usr/share/$package"
infodir="/var/lib/$package/info"
docsdir="/var/lib/$package/documents"

if [ "$DEBUG" ]; then
    echo entering $package postinst
    set -x
fi

reinstall_docs () {
    install-docs ${VERBOSE} --install-all
}

register_our_docs () {
    install-docs ${VERBOSE} --install $ctrldir/$package	\
		  		      $ctrldir/install-docs-man
}

case "$1" in
  configure)

    if dpkg --compare-versions "$2" lt-nl "$compat_ver" ||
      [ -z "`/bin/ls $infodir`" ]; then
	# version is less than last compatable version, we need to
	# re-register all the docs
        reinstall_docs
    else
        # only register our stuff
	register_our_docs
    fi
    ;;
  triggered)
    reinstall_docs
    ;; 	
esac

#DEBHELPER#

exit 0
