#!/bin/sh
# postinst for doc-base

# Abort if any command returns an error value
set -e

package=doc-base
# upgrades prior to this version require complete re-registration
compat_ver=0.8.1
# upgrades of the following version requires complete re-registration
bad_ver=0.7.13
VERBOSE=

ctrldir="/usr/share/$package"
infodir="/var/lib/$package/info"

if [ "$DEBUG" ]; then
    echo entering $package postinst
    set -x
fi

remove_obsolete( ) {
	# remove dhelp files
	find $infodir -maxdepth 1 -type f -name "*.list" | xargs grep -h '^/.*/.dhelp' |  \
	while read f; do 
		[ -e "$f" ] || continue;
		[ -x /usr/sbin/dhelp_parse ] && /usr/sbin/dhelp_parse -d "`dirname "$f"`" || true
		rm -f "$f"
	done

	find $infodir -maxdepth 1 -type f -name "*.list" | xargs rm -f
	
	# remove scrollkeeper files
	find $infodir -maxdepth 1 -type f -name "*.status" | \
	xargs sed -ne 's/^Scrollkeeper-omf-file: *\(.*-C.omf\) *$/\1/p'  |  \
	while read f; do 
		[ -e "$f" ] || continue;
		rm -f "$f"
		rmdir --ignore-fail-on-nonempty "`dirname "$f"`" || true
	done
}


reinstall_docs ( ) {
    
    # install all the existing doc-base control files
    num=`find /usr/share/$package/ -maxdepth 1 -type f | wc -l`
    echo "(re)registering $num documents from /usr/share/$package ..." >&2

    install-docs ${VERBOSE} --register-all || true  # don't abort on failure
}

case "$1" in
  configure)
    if [ "${2+set}" != set ] || [ -z "$2" ] || [ "$2" = "<unknown>" ] || [ ! -d /var/lib/doc-base/info ]; then
        # first install, or upgrade from ancient version, or install from removed-but-not-purged state
        reinstall_docs
    elif dpkg --compare-versions $2 lt $compat_ver; then
	# version is less than last compatable version, we need to
	# re-register all the docs
        reinstall_docs
    elif dpkg --compare-versions $2 eq $bad_ver; then
        # bad version, ew, re-register
        reinstall_docs
    else
        # only register our stuff
        install-docs ${VERBOSE} -i /usr/share/$package/$package	\
				-i /usr/share/$package/install-docs-man
    fi
    ;;
esac

#DEBHELPER#

exit 0
